### ISSUE TITLE
Support for remote repositories?

### ISSUE THREAD

**Issue by Ari-E-S** [thomasvandoren/puppet-etckeeper#14]
Hi!

I'm not puppet-savvy enough to implement this on my own...

I found 2 ways to implement this:
- either using a hook described in the [ArchLinux etckeeper manual](https://wiki.archlinux.org/index.php/Etckeeper#Automatic_push_to_remote_repo)
- or using the option PUSH_REMOTE in the latest [etckeeper.conf](https://github.com/joeyh/etckeeper/blob/master/etckeeper.conf)

Personally, I'd go with this:
1. adding the remote repo's URI as an optional parameter to your module
- setting `PUSH_REMOTE=origin` in etckeeper.conf
- and issuing the command `git remote add origin <repo_uri>`

The remote repo an the access to it must be prepared manually or by some other process.

What do you think? Can that be done?

Thanks!
    --Ariel

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
