### ISSUE TITLE
/etc/etckeeper directory created with conservative permissions

### ISSUE THREAD

**Issue by cpick** [thomasvandoren/puppet-etckeeper#2]
When I used this module to install etckeeper, puppet first created /etc/etckeeper (as prescribed), however it was created with mode 0750.
When installing etckeeper with apt-get, /etc/etckeeper was created with 0755 permissions.

Since it is useful to be able to look at etckeeper's permissions without superuser privileges, I think this module should create the directory with 0755.

**Comment by thomasvandoren** [comment]
Fixed in pull request #3.
